name: scrapl
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - cuda-nvcc
  - cuda-nvrtc
  - cuda-version=12.4
  - pip:
    - auraloss
    - black
    - einops
    - hypy-utils
    - jsonargparse[signatures]
    - librosa
    - lightning
    - matplotlib
    - msclap
    - nnaudio
    - numpy
    - nvitop
    - pandas
    - pip-chill
    - pyloudnorm
    - scipy
    - torch==2.8.0
    - torchaudio
    - torchcodec
    - torchvision
    - tensorboard
    - uv
    - wandb
    - git+https://github.com/christhetree/kymatio.git@702cfc0e002873de2b9ef83c9a0d3a831359e934
    - git+https://github.com/noahgolmant/pytorch-hessian-eigenthings.git@dce2e54a19963b0dfa41b93f531fb7742d46ea04

# uv pip install 'torch==2.8.0' lightning torchaudio torchvision torchcodec auraloss black 'jsonargparse[signatures]' librosa matplotlib msclap numpy nvitop pandas scipy tensorboard wandb pip-chill nnaudio pyloudnorm einops hypy-utils git+https://github.com/christhetree/kymatio.git@702cfc0e002873de2b9ef83c9a0d3a831359e934 git+https://github.com/noahgolmant/pytorch-hessian-eigenthings.git@dce2e54a19963b0dfa41b93f531fb7742d46ea04
